import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";
import {
  ArchiveRestore,
  CheckCircle2,
  CircleAlert,
  Database,
  FileCog,
  FolderOpen,
  GitBranch,
  HardDriveDownload,
  LayoutDashboard,
  ListChecks,
  PackageCheck,
  Play,
  RefreshCw,
  ScrollText,
  Settings,
  ShieldAlert,
  Square,
  Wrench,
  type LucideIcon,
} from "lucide-react";
import { useCallback, useEffect, useState } from "react";

type SyncRun = {
  status: string;
  startedAt: string;
  finishedAt: string;
  duration: string;
  details: string;
};

type SyncStatus = {
  schedulerRunning: boolean;
  startAllowed: boolean;
  statusText: string;
  nextRunText: string;
  publishedDatabase: string;
  latestResult: string;
  logDirectory: string;
  runs: SyncRun[];
};

type RepositoryStatus = {
  network_root: string;
  protocol_root: string;
  system_database: string;
  shared_available: boolean;
  initialized: boolean;
  membership_count: number;
  snapshot_id: string;
  snapshot_epoch_id: string;
  valid?: boolean;
  message?: string;
  missing?: string[];
};

type SchemaStatus = {
  system_database: string;
  business_database: string;
  state: string;
  installed_release_id?: string | null;
  installed_schema_version?: number | null;
  catalog_hash?: string | null;
  physical_fingerprint?: string | null;
  diagnostic?: string | null;
  last_validated_at?: string | null;
  last_migrated_at?: string | null;
  rollback_available?: boolean;
};

type SchemaPlan = SchemaStatus & {
  from_release_id?: string | null;
  to_release_id?: string | null;
  migrations?: Array<{
    migration_id: string;
    migration_kind: string;
    handler_name: string;
    destructive: boolean;
  }>;
};

type PortalReleaseStatus = {
  portableRoot: string;
  releaseRoot: string;
  packageVersion: string;
  currentReleaseVersion?: string | null;
  currentUpdateMode?: string | null;
  bootstrapVersion?: string | null;
  portalExe: string;
  systemDb: string;
};

type PageId =
  | "overview"
  | "source-data"
  | "repository"
  | "releases"
  | "schema"
  | "snapshots"
  | "backup"
  | "conflicts"
  | "logs"
  | "settings";

type NavigationItem = {
  id: PageId;
  label: string;
  icon: LucideIcon;
};

type PlannedModule = {
  title: string;
  description: string;
  tasks: string[];
  prerequisite: string;
};

const today = new Date().toISOString().slice(0, 10);

const navigation: NavigationItem[] = [
  { id: "overview", label: "Overview", icon: LayoutDashboard },
  { id: "source-data", label: "Source Data", icon: Database },
  { id: "repository", label: "Repository", icon: GitBranch },
  { id: "releases", label: "Releases", icon: PackageCheck },
  { id: "schema", label: "Schema", icon: FileCog },
  { id: "snapshots", label: "Snapshots", icon: HardDriveDownload },
  { id: "backup", label: "Backup", icon: ArchiveRestore },
  { id: "conflicts", label: "Conflicts", icon: ShieldAlert },
  { id: "logs", label: "Logs", icon: ScrollText },
  { id: "settings", label: "Settings", icon: Settings },
];

const plannedModules: Record<Exclude<PageId, "overview" | "source-data" | "repository" | "releases" | "schema">, PlannedModule> = {
  snapshots: {
    title: "Snapshots",
    description: "Build, validate, publish, inspect, and retain complete business-data snapshots.",
    tasks: ["Build snapshot", "Validate snapshot", "Publish snapshot", "Apply retention"],
    prerequisite: "Available after snapshot publication is registered as a Python task.",
  },
  backup: {
    title: "Backup",
    description: "Create, verify, restore, and retain independent backups of the business database.",
    tasks: ["Create backup", "Verify backup", "Restore plan", "Restore backup"],
    prerequisite: "Available after the backup and restore task implementation is registered.",
  },
  conflicts: {
    title: "Conflicts",
    description: "Review, export, and resolve conflict reports generated by the data coordinator.",
    tasks: ["List conflicts", "Export selected conflicts", "Apply resolution"],
    prerequisite: "Available when conflict reporting and resolution commands are packaged.",
  },
  logs: {
    title: "Logs",
    description: "Filter task history by date, task, severity, and correlation ID.",
    tasks: ["Browse run history", "Open diagnostic log", "Export task results"],
    prerequisite: "Available after all workstation tasks write the shared structured run history.",
  },
  settings: {
    title: "Settings",
    description: "Validate workstation paths, runtime dependencies, and approved configuration changes.",
    tasks: ["Check shared paths", "Check Python runtime", "Validate settings", "Review configuration changes"],
    prerequisite: "Available when validated settings edits are implemented in the Python task runner.",
  },
};

function formatDate(value: string) {
  return new Intl.DateTimeFormat("en-US", {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(new Date(value + "T00:00:00"));
}

function PlannedWorkspace({ module }: { module: PlannedModule }) {
  return (
    <section className="planned-workspace">
      <div className="workspace-intro">
        <p className="eyebrow">WORKSTATION MODULE</p>
        <h2>{module.title}</h2>
        <p>{module.description}</p>
      </div>
      <section className="availability-notice">
        <CircleAlert size={20} />
        <div>
          <strong>Task runner not registered yet</strong>
          <p>{module.prerequisite}</p>
        </div>
      </section>
      <section className="task-list" aria-label={`${module.title} planned operations`}>
        {module.tasks.map((task) => (
          <div className="task-row" key={task}>
            <span>{task}</span>
            <button className="quiet-button" disabled>Unavailable</button>
          </div>
        ))}
      </section>
    </section>
  );
}

function Overview({ status, navigate }: { status: SyncStatus | null; navigate: (page: PageId) => void }) {
  const modules = navigation.filter((item) => item.id !== "overview");
  return (
    <section className="overview-workspace">
      <div className="workspace-intro">
        <p className="eyebrow">WORKSTATION HEALTH</p>
        <h2>Overview</h2>
        <p>Review source synchronization and open a maintenance module.</p>
      </div>
      <section className="metrics overview-metrics">
        <div>
          <span>SOURCE SCHEDULER</span>
          <strong>{status?.schedulerRunning ? "Running" : "Stopped"}</strong>
        </div>
        <div>
          <span>LATEST RESULT</span>
          <strong>{status?.latestResult ?? "Checking"}</strong>
        </div>
        <div>
          <span>ACTIVE PUBLICATION</span>
          <strong className="path"><Database size={16} />{status?.publishedDatabase ?? "Checking"}</strong>
        </div>
      </section>
      <section className="module-grid" aria-label="Workstation modules">
        {modules.map((item) => {
          const Icon = item.icon;
          const available = item.id === "source-data" || item.id === "repository" || item.id === "schema";
          return (
            <button className="module-link" key={item.id} onClick={() => navigate(item.id)}>
              <Icon size={20} />
              <span>
                <strong>{item.label}</strong>
                <small>{available ? "Available" : "Task runner pending"}</small>
              </span>
            </button>
          );
        })}
      </section>
    </section>
  );
}

function SchemaWorkspace({
  status,
  plan,
  busy,
  confirmation,
  setConfirmation,
  refresh,
  validate,
  loadPlan,
  execute,
}: {
  status: SchemaStatus | null;
  plan: SchemaPlan | null;
  busy: string | null;
  confirmation: string;
  setConfirmation: (value: string) => void;
  refresh: () => void;
  validate: () => void;
  loadPlan: () => void;
  execute: (action: "initialize" | "migrate" | "rollback") => void;
}) {
  const requiresInitialization = status?.state === "unmanaged";
  const isHealthy = status?.state === "healthy";
  const migrations = plan?.migrations ?? [];
  const confirmationMatches = confirmation.trim() === status?.business_database;
  const stateLabel = status?.state ? status.state.replaceAll("_", " ").toUpperCase() : "CHECKING";

  return (
    <section className="schema-workspace">
      <div className="workspace-intro workspace-intro-row">
        <div>
          <p className="eyebrow">LOCAL BUSINESS DATABASE</p>
          <h2>Schema Maintenance</h2>
          <p>Inspect, validate, install, migrate, and recover the local business database through approved Python handlers.</p>
        </div>
        <div className="actions">
          <button className="quiet-button" disabled={busy !== null} onClick={refresh}>
            <RefreshCw size={17} />
            {busy === "status" ? "Checking" : "Refresh"}
          </button>
          <button className="quiet-button" disabled={busy !== null} onClick={validate}>
            <CheckCircle2 size={17} />
            {busy === "validate" ? "Validating" : "Validate"}
          </button>
          <button className="primary-button" disabled={busy !== null} onClick={loadPlan}>
            <ListChecks size={17} />
            {busy === "plan" ? "Planning" : "Plan"}
          </button>
        </div>
      </div>

      <section className={isHealthy ? "status running" : "status stopped"}>
        <div>
          <p className="eyebrow">SCHEMA STATUS</p>
          <h2>{stateLabel}</h2>
          <p>{status?.diagnostic || (isHealthy ? "The installed schema matches the active catalog release." : "Review the database status before making a schema change.")}</p>
        </div>
      </section>

      <section className="metrics schema-metrics" aria-label="Schema database status">
        <div><span>INSTALLED RELEASE</span><strong>{status?.installed_release_id || "Not installed"}</strong></div>
        <div><span>SCHEMA VERSION</span><strong>{status?.installed_schema_version ?? "-"}</strong></div>
        <div><span>LAST VALIDATED</span><strong>{status?.last_validated_at || "-"}</strong></div>
      </section>

      <section className="schema-details">
        <div><span>System catalog</span><strong>{status?.system_database || "Checking configuration"}</strong></div>
        <div><span>Business database</span><strong>{status?.business_database || "Checking configuration"}</strong></div>
        <div><span>Catalog hash</span><strong>{status?.catalog_hash || "-"}</strong></div>
      </section>

      <section className="schema-plan" aria-label="Schema migration plan">
        <div className="table-toolbar">
          <div>
            <p className="eyebrow">MIGRATION PLAN</p>
            <h2>{plan ? `${plan.from_release_id || "Unmanaged"} to ${plan.to_release_id || "Active release"}` : "Load a plan before changing the database"}</h2>
          </div>
        </div>
        <div className="table-scroll">
          <table>
            <thead><tr><th>Migration</th><th>Kind</th><th>Handler</th><th>Data rebuild</th></tr></thead>
            <tbody>
              {migrations.map((migration) => (
                <tr key={migration.migration_id}>
                  <td>{migration.migration_id}</td><td>{migration.migration_kind}</td><td>{migration.handler_name}</td><td>{migration.destructive ? "Yes" : "No"}</td>
                </tr>
              ))}
              {plan && !migrations.length && <tr><td colSpan={4} className="empty compact-empty">No migration is required for the active release.</td></tr>}
              {!plan && <tr><td colSpan={4} className="empty compact-empty">No migration plan has been loaded.</td></tr>}
            </tbody>
          </table>
        </div>
      </section>

      <section className="schema-actions">
        <div>
          <p className="eyebrow">CONFIRM DATABASE CHANGE</p>
          <p>Type the configured business database path to enable install, migration, or rollback.</p>
        </div>
        <input aria-label="Business database confirmation" value={confirmation} placeholder={status?.business_database || "Business database path"} onChange={(event) => setConfirmation(event.target.value)} />
        <div className="actions">
          <button className="primary-button" disabled={!requiresInitialization || !confirmationMatches || busy !== null} onClick={() => execute("initialize")}>
            <Wrench size={17} /> {busy === "initialize" ? "Installing" : "Install baseline"}
          </button>
          <button className="primary-button" disabled={!migrations.length || !confirmationMatches || busy !== null} onClick={() => execute("migrate")}>
            <FileCog size={17} /> {busy === "migrate" ? "Migrating" : "Apply migration"}
          </button>
          <button className="danger-button" disabled={!status?.rollback_available || !confirmationMatches || busy !== null} onClick={() => execute("rollback")}>
            <ArchiveRestore size={17} /> {busy === "rollback" ? "Restoring" : "Restore previous"}
          </button>
        </div>
      </section>
    </section>
  );
}

function RepositoryWorkspace({
  status,
  busy,
  networkRoot,
  setNetworkRoot,
  refresh,
  validate,
  bootstrap,
}: {
  status: RepositoryStatus | null;
  busy: "refresh" | "validate" | "bootstrap" | null;
  networkRoot: string;
  setNetworkRoot: (value: string) => void;
  refresh: () => void;
  validate: () => void;
  bootstrap: (networkRoot: string) => void;
}) {
  const initialized = status?.initialized ?? false;
  const sharedAvailable = status?.shared_available ?? false;
  return (
    <section className="repository-workspace">
      <div className="workspace-intro workspace-intro-row">
        <div>
          <p className="eyebrow">SHARED BUSINESS DATA</p>
          <h2>Repository</h2>
          <p>Inspect the configured shared repository and validate its active membership and snapshot.</p>
        </div>
        <div className="actions">
          <button className="primary-button" disabled={!initialized || busy !== null} onClick={validate}>
            <ShieldAlert size={17} />
            {busy === "validate" ? "Validating" : "Validate"}
          </button>
        </div>
      </div>

      <section className={sharedAvailable ? "status running" : "status stopped"}>
        <div>
          <p className="eyebrow">REPOSITORY STATUS</p>
          <h2>{initialized ? "INITIALIZED" : sharedAvailable ? "NOT INITIALIZED" : "UNAVAILABLE"}</h2>
          <p>{status?.message ?? (sharedAvailable ? "The shared location is available." : "Checking the configured shared location.")}</p>
        </div>
      </section>

      <section className="metrics repository-metrics" aria-label="Repository status">
        <div>
          <span>MEMBERS</span>
          <strong>{status?.membership_count ?? "-"}</strong>
        </div>
        <div>
          <span>ACTIVE SNAPSHOT</span>
          <strong>{status?.snapshot_id || "-"}</strong>
        </div>
        <div>
          <span>SNAPSHOT EPOCH</span>
          <strong>{status?.snapshot_epoch_id || "-"}</strong>
        </div>
      </section>

      <section className="repository-details">
        <div><span>Shared repository</span><strong>{status?.network_root ?? "Checking configuration"}</strong></div>
        <div><span>Protocol root</span><strong>{status?.protocol_root ?? "-"}</strong></div>
        <div><span>System database</span><strong>{status?.system_database ?? "-"}</strong></div>
      </section>

      {!initialized && sharedAvailable && (
        <section className="repository-bootstrap">
          <div>
            <p className="eyebrow">INITIALIZE REPOSITORY</p>
            <h3>Shared repository path</h3>
            <p>Initialization creates the shared protocol structure and initial membership release. Change the configured path here when needed.</p>
          </div>
          <div className="bootstrap-controls">
            <input
              aria-label="Shared repository path"
              value={networkRoot}
              placeholder="Shared repository path"
              onChange={(event) => setNetworkRoot(event.target.value)}
            />
            <button
              className="danger-button"
              disabled={busy !== null || !networkRoot.trim()}
              onClick={() => bootstrap(networkRoot.trim())}
            >
              <Database size={17} />
              {busy === "bootstrap" ? "Initializing" : "Initialize"}
            </button>
          </div>
        </section>
      )}
    </section>
  );
}

function ReleaseWorkspace({
  status,
  updateMode,
  releaseVersion,
  busy,
  progress,
  success,
  setUpdateMode,
  setReleaseVersion,
  publish,
}: {
  status: PortalReleaseStatus | null;
  updateMode: "system-db" | "portal-exe" | "full";
  releaseVersion: string;
  busy: boolean;
  progress: string;
  success: string;
  setUpdateMode: (value: "system-db" | "portal-exe" | "full") => void;
  setReleaseVersion: (value: string) => void;
  publish: () => void;
}) {
  const targeted = updateMode !== "full";
  return (
    <section className="release-workspace">
      <div className="workspace-intro workspace-intro-row">
        <div>
          <p className="eyebrow">PORTABLE DISTRIBUTION</p>
          <h2>Releases</h2>
          <p>Publish the selected Portal update to the configured shared release location.</p>
        </div>
      </div>

      <section className="metrics release-metrics" aria-label="Portal release status">
        <div><span>PACKAGE VERSION</span><strong>{status?.packageVersion ?? "-"}</strong></div>
        <div><span>CURRENT RELEASE</span><strong>{status?.currentReleaseVersion ?? "Not published"}</strong></div>
        <div><span>BOOTSTRAP BUNDLE</span><strong>{status?.bootstrapVersion ?? "Not published"}</strong></div>
      </section>

      <section className="release-details">
        <div><span>Portable folder</span><strong>{status?.portableRoot ?? "Checking configuration"}</strong></div>
        <div><span>Release folder</span><strong>{status?.releaseRoot ?? "-"}</strong></div>
        <div><span>System database</span><strong>{status?.systemDb ?? "-"}</strong></div>
        <div><span>Portal executable</span><strong>{status?.portalExe ?? "-"}</strong></div>
      </section>

      <section className="release-controls">
        <div>
          <p className="eyebrow">PUBLISH UPDATE</p>
          <h3>Select the exact update type</h3>
          <p>A full release is required for the Python runtime, multiple files, or structural changes.</p>
        </div>
        <label>
          Update type
          <select value={updateMode} onChange={(event) => setUpdateMode(event.target.value as typeof updateMode)}>
            <option value="system-db">System database only</option>
            <option value="portal-exe">Portal executable only</option>
            <option value="full">Full portable folder</option>
          </select>
        </label>
        <label>
          Release version
          <input
            value={releaseVersion}
            placeholder={status?.packageVersion ?? "0.0.0"}
            onChange={(event) => setReleaseVersion(event.target.value)}
          />
        </label>
        <button
          className="primary-button"
          disabled={busy || !status || (targeted && !releaseVersion.trim())}
          onClick={publish}
        >
          <PackageCheck size={17} />
          {busy ? "Publishing" : "Publish release"}
        </button>
      </section>

      {busy && (
        <section className="release-feedback progress" aria-live="polite">
          <RefreshCw size={19} className="spin" />
          <div>
            <strong>Publishing release</strong>
            <p>{progress || "Preparing the release."}</p>
          </div>
        </section>
      )}
      {!busy && success && (
        <section className="release-feedback success" aria-live="polite">
          <CheckCircle2 size={20} />
          <div>
            <strong>Release published successfully</strong>
            <p>{success}</p>
          </div>
        </section>
      )}
    </section>
  );
}

function SourceDataWorkspace({
  status,
  selectedDate,
  setSelectedDate,
  busy,
  execute,
  openLogs,
}: {
  status: SyncStatus | null;
  selectedDate: string;
  setSelectedDate: (date: string) => void;
  busy: "start" | "stop" | null;
  execute: (action: "start" | "stop") => void;
  openLogs: () => void;
}) {
  const isRunning = status?.schedulerRunning ?? false;
  return (
    <section className="source-workspace">
      <section className={isRunning ? "status running" : "status stopped"}>
        <div>
          <p className="eyebrow">SOURCE DATA SCHEDULER</p>
          <h2>{status?.statusText ?? "CHECKING"}</h2>
          <p>{isRunning ? "Automatic source synchronization is active." : "The source scheduler is not running."}</p>
        </div>
        <div className="actions">
          <button
            className="primary-button"
            disabled={isRunning || !status?.startAllowed || busy !== null}
            onClick={() => execute("start")}
          >
            <Play size={17} />
            {busy === "start" ? "Starting" : "Start"}
          </button>
          <button
            className="danger-button"
            disabled={!isRunning || busy !== null}
            onClick={() => execute("stop")}
          >
            <Square size={16} />
            {busy === "stop" ? "Stopping" : "Stop"}
          </button>
          <button className="quiet-button" onClick={openLogs} disabled={!status?.logDirectory}>
            <FolderOpen size={17} />
            Open logs
          </button>
        </div>
      </section>

      <section className="metrics" aria-label="Source synchronization status">
        <div>
          <span>ACTIVITY</span>
          <strong>{isRunning ? "Schedule active" : "Not running"}</strong>
        </div>
        <div>
          <span>NEXT RUN</span>
          <strong>{status?.nextRunText ?? "-"}</strong>
        </div>
        <div>
          <span>PUBLISHED DATABASE</span>
          <strong className="path"><Database size={16} />{status?.publishedDatabase ?? "Not published"}</strong>
        </div>
        <div>
          <span>LATEST RESULT</span>
          <strong>{status?.latestResult ?? "No runs recorded"}</strong>
        </div>
      </section>

      <section className="runs">
        <div className="table-toolbar">
          <div>
            <p className="eyebrow">SYNCHRONIZATION RUNS</p>
            <h2>{formatDate(selectedDate)}</h2>
          </div>
          <label>
            Date
            <input type="date" value={selectedDate} onChange={(event) => setSelectedDate(event.target.value)} />
          </label>
        </div>
        <div className="table-scroll">
          <table>
            <thead>
              <tr>
                <th>Status</th>
                <th>Started</th>
                <th>Finished</th>
                <th>Duration</th>
                <th>Details</th>
              </tr>
            </thead>
            <tbody>
              {(status?.runs ?? []).map((run, index) => (
                <tr key={[run.startedAt, index].join("-")}>
                  <td data-status={run.status}>{run.status}</td>
                  <td>{run.startedAt}</td>
                  <td>{run.finishedAt}</td>
                  <td>{run.duration}</td>
                  <td>{run.details}</td>
                </tr>
              ))}
              {!status?.runs.length && (
                <tr>
                  <td colSpan={5} className="empty">No synchronization attempts were recorded for this date.</td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </section>
    </section>
  );
}

export function App() {
  const [activePage, setActivePage] = useState<PageId>("overview");
  const [selectedDate, setSelectedDate] = useState(today);
  const [status, setStatus] = useState<SyncStatus | null>(null);
  const [repositoryStatus, setRepositoryStatus] = useState<RepositoryStatus | null>(null);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState<"start" | "stop" | null>(null);
  const [repositoryBusy, setRepositoryBusy] = useState<"refresh" | "validate" | "bootstrap" | null>(null);
  const [repositoryNetworkRoot, setRepositoryNetworkRoot] = useState("");
  const [releaseStatus, setReleaseStatus] = useState<PortalReleaseStatus | null>(null);
  const [releaseMode, setReleaseMode] = useState<"system-db" | "portal-exe" | "full">("full");
  const [releaseVersion, setReleaseVersion] = useState("");
  const [releaseBusy, setReleaseBusy] = useState(false);
  const [releaseProgress, setReleaseProgress] = useState("");
  const [releaseSuccess, setReleaseSuccess] = useState("");
  const [schemaStatus, setSchemaStatus] = useState<SchemaStatus | null>(null);
  const [schemaPlan, setSchemaPlan] = useState<SchemaPlan | null>(null);
  const [schemaBusy, setSchemaBusy] = useState<string | null>(null);
  const [schemaConfirmation, setSchemaConfirmation] = useState("");

  const refresh = useCallback(async () => {
    try {
      const response = await invoke<SyncStatus>("sync_status", { selectedDate });
      setStatus(response);
      setError("");
    } catch (reason) {
      setError(String(reason));
    }
  }, [selectedDate]);

  useEffect(() => {
    void refresh();
    const interval = window.setInterval(() => void refresh(), 5000);
    return () => window.clearInterval(interval);
  }, [refresh]);

  useEffect(() => {
    let unlisten: (() => void) | undefined;
    void listen<string>("portal-release-progress", (event) => {
      setReleaseProgress(event.payload);
    }).then((dispose) => {
      unlisten = dispose;
    });
    return () => unlisten?.();
  }, []);

  const refreshRepository = useCallback(async () => {
    setRepositoryBusy("refresh");
    try {
      const response = await invoke<RepositoryStatus>("repository_status");
      setRepositoryStatus(response);
      setRepositoryNetworkRoot(response.network_root);
      setError("");
    } catch (reason) {
      setError(String(reason));
    } finally {
      setRepositoryBusy(null);
    }
  }, []);

  useEffect(() => {
    if (activePage === "repository") {
      void refreshRepository();
    }
  }, [activePage, refreshRepository]);

  const refreshRelease = useCallback(async () => {
    try {
      const response = await invoke<PortalReleaseStatus>("portal_release_status");
      setReleaseStatus(response);
      setReleaseVersion((current) => current || response.packageVersion);
      setError("");
    } catch (reason) {
      setError(String(reason));
    }
  }, []);

  useEffect(() => {
    if (activePage === "releases") {
      void refreshRelease();
    }
  }, [activePage, refreshRelease]);

  const schemaTask = useCallback(async (task: "status" | "validate" | "plan" | "initialize" | "migrate" | "rollback", confirmation?: string) => {
    setSchemaBusy(task);
    try {
      const command = task === "status" ? "schema_status" : task === "validate" ? "validate_schema" : task === "plan" ? "plan_schema" : task === "initialize" ? "initialize_schema" : task === "migrate" ? "migrate_schema" : "rollback_schema";
      const response = await invoke<SchemaStatus | SchemaPlan>(command, confirmation === undefined ? {} : { confirmation });
      if (task === "plan") setSchemaPlan(response as SchemaPlan);
      else setSchemaStatus(response as SchemaStatus);
      if (task === "initialize" || task === "migrate" || task === "rollback") {
        setSchemaConfirmation("");
        setSchemaPlan(null);
      }
      setError("");
    } catch (reason) {
      setError(String(reason));
    } finally {
      setSchemaBusy(null);
    }
  }, []);

  useEffect(() => {
    if (activePage === "schema") void schemaTask("status");
  }, [activePage, schemaTask]);

  const execute = async (action: "start" | "stop") => {
    setBusy(action);
    try {
      await invoke(action === "start" ? "start_scheduler" : "stop_scheduler");
      await new Promise((resolve) => window.setTimeout(resolve, 600));
      await refresh();
    } catch (reason) {
      setError(String(reason));
    } finally {
      setBusy(null);
    }
  };

  const openLogs = async () => {
    try {
      await invoke("open_path", { path: status?.logDirectory ?? "" });
    } catch (reason) {
      setError(String(reason));
    }
  };

  const validateRepository = async () => {
    setRepositoryBusy("validate");
    try {
      const response = await invoke<RepositoryStatus>("validate_repository");
      setRepositoryStatus(response);
      setError("");
    } catch (reason) {
      setError(String(reason));
    } finally {
      setRepositoryBusy(null);
    }
  };

  const bootstrapRepository = async (networkRoot: string) => {
    if (!networkRoot) {
      return;
    }
    setRepositoryBusy("bootstrap");
    try {
      const response = await invoke<RepositoryStatus>("bootstrap_repository", {
        networkRoot,
      });
      setRepositoryStatus(response);
      setRepositoryNetworkRoot(response.network_root);
      setError("");
    } catch (reason) {
      setError(String(reason));
    } finally {
      setRepositoryBusy(null);
    }
  };

  const publishRelease = async () => {
    const version = releaseVersion.trim() || undefined;
    const label = releaseMode === "system-db" ? "system database only" : releaseMode === "portal-exe" ? "Portal executable only" : "the full portable folder";
    if (!window.confirm(`Publish ${label} as release ${version ?? releaseStatus?.packageVersion ?? ""}?`)) {
      return;
    }
    setReleaseSuccess("");
    setReleaseProgress("Preparing the release.");
    setReleaseBusy(true);
    try {
      const response = await invoke<PortalReleaseStatus>("publish_portal_release", {
        updateMode: releaseMode,
        releaseVersion: version,
      });
      setReleaseStatus(response);
      setReleaseVersion(response.currentReleaseVersion ?? response.packageVersion);
      setReleaseSuccess(`${response.currentUpdateMode ?? releaseMode} release ${response.currentReleaseVersion ?? response.packageVersion} is available at ${response.releaseRoot}.`);
      setError("");
    } catch (reason) {
      setError(String(reason));
    } finally {
      setReleaseBusy(false);
    }
  };

  const activeLabel = navigation.find((item) => item.id === activePage)?.label ?? "Overview";

  return (
    <main className="app-shell">
      <aside className="sidebar">
        <div className="brand">
          <p className="eyebrow">PORTAL WORKSTATION</p>
          <strong>Manager</strong>
        </div>
        <nav aria-label="Workstation functions">
          {navigation.map((item) => {
            const Icon = item.icon;
            return (
              <button
                className={item.id === activePage ? "navigation-link active" : "navigation-link"}
                key={item.id}
                onClick={() => setActivePage(item.id)}
              >
                <Icon size={18} />
                {item.label}
              </button>
            );
          })}
        </nav>
        <div className="sidebar-footer">
          <span>Standalone desktop app</span>
          <span>Python task coordinator</span>
        </div>
      </aside>

      <section className="workspace-shell">
        <header className="app-header">
          <div>
            <p className="eyebrow">PORTAL WORKSTATION</p>
            <h1>{activeLabel}</h1>
          </div>
          <button
            className="quiet-button"
            onClick={() => void (activePage === "repository" ? refreshRepository() : activePage === "releases" ? refreshRelease() : refresh())}
            title="Refresh status"
          >
            <RefreshCw size={18} />
            Refresh
          </button>
        </header>

        {error && (
          <section className="notice error">
            <CircleAlert size={18} />
            <span>{error}</span>
          </section>
        )}

        {activePage === "overview" && <Overview status={status} navigate={setActivePage} />}
        {activePage === "source-data" && (
          <SourceDataWorkspace
            busy={busy}
            execute={(action) => void execute(action)}
            openLogs={() => void openLogs()}
            selectedDate={selectedDate}
            setSelectedDate={setSelectedDate}
            status={status}
          />
        )}
        {activePage === "repository" && (
          <RepositoryWorkspace
            bootstrap={(networkRoot) => void bootstrapRepository(networkRoot)}
            busy={repositoryBusy}
            networkRoot={repositoryNetworkRoot}
            refresh={() => void refreshRepository()}
            setNetworkRoot={setRepositoryNetworkRoot}
            status={repositoryStatus}
            validate={() => void validateRepository()}
          />
        )}
        {activePage === "releases" && (
          <ReleaseWorkspace
            busy={releaseBusy}
            progress={releaseProgress}
            releaseVersion={releaseVersion}
            setReleaseVersion={setReleaseVersion}
            setUpdateMode={setReleaseMode}
            status={releaseStatus}
            success={releaseSuccess}
            updateMode={releaseMode}
            publish={() => void publishRelease()}
          />
        )}
        {activePage === "schema" && (
          <SchemaWorkspace
            busy={schemaBusy}
            confirmation={schemaConfirmation}
            execute={(action) => void schemaTask(action, schemaConfirmation)}
            loadPlan={() => void schemaTask("plan")}
            plan={schemaPlan}
            refresh={() => void schemaTask("status")}
            setConfirmation={setSchemaConfirmation}
            status={schemaStatus}
            validate={() => void schemaTask("validate")}
          />
        )}
        {activePage !== "overview" && activePage !== "source-data" && activePage !== "repository" && activePage !== "releases" && activePage !== "schema" && (
          <PlannedWorkspace module={plannedModules[activePage]} />
        )}
      </section>
    </main>
  );
}
